### ISSUE TITLE
Anyone have any luck on an Amazon Fire TV with Kodi and this Lynda plug-in?

### ISSUE THREAD

**Issue by githubuser612** [davejm/plugin.video.lynda#1]
Anyone have any luck on an Amazon Fire TV with Kodi and this Lynda plug-in?
I'm getting an "Add-on does not have the correct structure" error.

**Comment by davejm** [comment]
Hi @githubuser612, any chance you could submit the relevant section of your kodi.log file so I can see what's happening when you try to load the app?

**Comment by githubuser612** [comment]
I hope this screenshot works and means something to you as I couldn't transfer the log to my pc from my Amazon Fire TV.
![log](https://cloud.githubusercontent.com/assets/16965693/12771535/fa067ffe-c9f7-11e5-9e38-c55a0232f5d3.JPG)

Thanks @davejm !

**Comment by davejm** [comment]
@githubuser612 I don't see an error relating to my addon in that section of your log. Does Kodi work correctly for your other plugins? I checked my addon structure against the standard and it looks correct + I haven't been able to replicate this. Any luck since then?

**Comment by githubuser612** [comment]
I never did have any luck and gave up.

**Comment by davejm** [comment]
@githubuser612 I know this is old but I think the latest version fixes this issue. Logging in for organisational accounts may be broken at the moment though.

**Comment by davejm** [comment]
Closed for inactivity
