### ISSUE TITLE
Issue login via organization

### ISSUE THREAD

**Issue by prof-ninjason** [davejm/plugin.video.lynda#3]
I cannot login via my university's special link. I also tried using just the domain. 
These work in the Lynda app and website. 
URL: http://go.uic.edu/lynda
Domain: uic.edu

**Comment by davejm** [comment]
Looks like the login pages have been relocated and restyled. I'll have a look!

**Comment by davejm** [comment]
Hi @jcrochon. Try again with the latest repo snapshot and your domain being 'uic.edu'. Should be working. Please confirm. Thanks

**Comment by prof-ninjason** [comment]
Looks like it's connecting now. I have an issue on my side with SSL errors on forwarding between shibboleth, login.uic.edu and ness.uic.edu

I'm going to build a VM at work to see if there are any issues. Next, I'll test at home via VPN.
