### ISSUE TITLE
"Normal" Login Functionality

### ISSUE THREAD

**Issue by WhereRtheInterwebs** [davejm/plugin.video.lynda#7]
You mentioned you needed people to help test the "normal" login.  I have this and am willing to help test if there is anything I can do.

**Comment by davejm** [comment]
Thanks @WhereRtheInterwebs and @lcammo for volunteering. I've pushed a first stab in the dark to https://github.com/davejm/plugin.video.lynda/tree/normal-login. If you could test that out and see if it works as a first step that would be useful. Thanks!

**Comment by davejm** [comment]
Make sure to set the relevant settings in the addon settings.

**Comment by dannoe** [comment]
Doesn't work for me. It just says "Could not login. Please check your credentials are correct."
And I am 100% sure they are correct.

**Comment by davejm** [comment]
Thanks for testing @dannoe. Could you please try logging in on a browser such as Chrome? With the Developer tools open on the network tab (and 'preserve log' checked in case you get redirected), could you tell me about any relevant requests that happen when you click sign in?

I have replicated the POST request to 'https://www.lynda.com/ajax/signin/password' that happens after you enter your username/email. The next screen asks for your password. Submitting that form POSTs to 'https://www.lynda.com/ajax/signin/user'. Can you tell me about that response? Or what happens after that? I'd rather not have a full network log as I don't want your password or cookies.

**Comment by dannoe** [comment]
POST https://www.lynda.com/ajax/signin/user
Response 200: {"AuthenticationErrors":0,"UserID":12345,"Token":null,"RedirectUrl":"/","HasErrors":false,"ErrorMessage":null,"Concurrent":false,"Url":null}

Long version including the request header:
https://gist.github.com/dannoe/3ec112c4686c290e1f33d7ce46719f96

**Comment by davejm** [comment]
Ok thanks. Is there another POST after that? Or does it just redirect to https://www.lynda.com (most likely via a 'location' response header from the POST you sent me)?

**Comment by dannoe** [comment]
No there isn't. The next request is the GET on https://www.lynda.com/. I think it's probably done via JS and the "RedirectUrl" from the JSON Response in my previous post.

**Comment by davejm** [comment]
Cheers. Please try the latest code on the normal-login branch.

**Comment by dannoe** [comment]
It's working. There's only a very trivial error left: It couldn't get my name. It just says "Logged in as Can't get name"

There are two possibilities to get the name:
`<ul id="submenu-profile" title="" class="submenu-profile" data-original-title="Daniel">`
or
`<span class="account-name" data-qa="eyebrow_account_menu">Hi Daniel</span>`

Thanks for your efforts!

**Comment by davejm** [comment]
@dannoe no problem. Glad it's working! Ok, hopefully just pushed a fix for the name. Please could you check?

**Comment by dannoe** [comment]
Yes that fixed it. Great work. Thanks again.

**Comment by davejm** [comment]
Brilliant. No problem. Glad this feature is done!

**Comment by davejm** [comment]
Merged to master
